#!/bin/sh
. ${CONFIG};

module_start()
{
    space=`df 2>/dev/null | grep /data | grep Glob | awk '{ print $4 }'`;
    if [ $space -lt 25000 ]; then
        find /data/.boxee/UserData/profiles/*/Thumbnails/ -name \*.tbn | xargs rm;
    fi;
    started_module "cleanup";
}

module_stop()
{
    stopped_module "cleanup";
}

case "$1" in
    start)
        module_start;
    ;;

    stop)
        module_stop;
    ;;

    enable|disable)
    ;;
esac;
