#!/bin/sh
# requires: writable_etc
. ${CONFIG};
DROPBEARDIR=/etc/dropbear

module_start()
{
    require_modules "writable_etc";
    [ -d ${DROPBEARDIR} ] || mkdir -p ${DROPBEARDIR};
    [ -f ${DROPBEARDIR}/dropbear_rsa_host_key ] || dropbearkey -t rsa -f ${DROPBEARDIR}/dropbear_rsa_host_key;
    [ -f ${DROPBEARDIR}/dropbear_dss_host_key ] || dropbearkey -t dss -f ${DROPBEARDIR}/dropbear_dss_host_key;
    dropbear &
    started_module "dropbear";
}

module_stop()
{
    killall dropbear;
    stopped_module "dropbear";
}

case "$1" in
    start)
        module_start;
    ;;

    stop)
        module_stop;
    ;;

    enable)
        echo "NOTICE: Nothing to prepare, preparations in start because of writable_etc.";
    ;;

    disable)
    ;;
esac;
