#!/bin/sh
. ${CONFIG};
SPLASHDIR=${PERSISTENTDIR}/splash

module_enable()
{
    if [ ! -d ${SPLASHDIR} ];
    then
        mkdir -p ${SPLASHDIR}/Fonts;
        cp -aR ${INSTALLDIR}/data/splash/* ${SPLASHDIR};
        cp -aR /opt/boxee/media/Fonts/* ${SPLASHDIR}/Fonts/;
    fi;
}

module_disable()
{
    rm -Rf ${SPLASHDIR};
}

module_start()
{
    mount -o bind ${SPLASHDIR} /opt/boxee/media &&
        started_module "splash";
}

module_stop()
{
    umount -f /opt/boxee/media &&
        stopped_module "splash";
}

case "$1" in
    start)
        module_start;
    ;;

    stop)
        module_stop;
    ;;

    enable)
        module_enable;
    ;;

    disable)
        module_disable;
    ;;
esac;
