#!/bin/sh
. ${CONFIG};
ETCDIR=${PERSISTENTDIR}/etc

module_start()
{
    mount -o bind ${ETCDIR} /etc &&
        started_module "writable_etc";
}

module_stop()
{
    umount -f /etc &&
        stopped_module "writable_etc";
}

module_enable()
{
    # Make root home directory
    mkdir -p /data/root
    chmod 0644 /data/root

    # Copy /etc to make it writable
    if [ ! -d ${ETCDIR} ];
    then
        cp -aR /etc ${ETCDIR}
        cp -aR ${INSTALLDIR}/data/etc/* ${ETCDIR}
    fi;
}

case "$1" in
    start)
        module_start;
    ;;

    stop)
        module_stop;
    ;;

    enable)
        module_enable;
    ;;

    disable)
        echo "NOTICE: Disable not available.";
    ;;
esac;
