#!/bin/sh
_PLUGINS="/tmp/boxeehack-plugins-started";

started_module()
{
    touch ${_PLUGINS}/.$1;
}

require_plugins()
{
    # that probably should be different
    for plugin in $@;
    do
        # waiting until file appears
        while [ ! -e "${_PLUGINS}/.${plugin}" ];
        do
            sleep 1;
        done;
    done;
}

stopped_plugin()
{
    rm -f ${_PLUGINS}/.$1;
}
