#!/bin/sh
. `dirname $0`/config;

boxeehack_start()
{
    mkdir -p ${_MODULES};
    if [ -z "$1" ];
    then
        echo "Starting all modules";
        for module in ${INSTALLDIR}/modules-enabled/*;
        do
            CONFIG=${INSTALLDIR}/config ${module} start &
        done;

    elif [ -x "${INSTALLDIR}/modules-enabled/$1" ];
    then
        echo "Starting $1 module.";
        CONFIG=${INSTALLDIR}/config ${INSTALLDIR}/modules-enabled/$1 start;

    else
        echo "Invalid module!";
        exit 5;
    fi;
}

boxeehack_stop()
{
    if [ -z "$1" ];
    then
        echo "Stopping all modules";
        for module in ${INSTALLDIR}/modules-enabled/*;
        do
            CONFIG=${INSTALLDIR}/config ${module} stop;
        done;

    elif [ -x "${INSTALLDIR}/modules-enabled/$1" ];
    then
        echo "Stopping $1 module.";
        CONFIG=${INSTALLDIR}/config ${INSTALLDIR}/modules-enabled/$1 stop;

    else
        echo "Invalid module!";
        exit 6;
    fi;
}

boxeehack_install()
{
    echo "Installing Boxee+Hacks";
    mkdir -p ${PERSISTENTDIR};
    chmod +x ${INSTALLDIR}/bin/*;
    # installing default modules
    chmod +x ${INSTALLDIR}/modules-available/*;
    for module in ${INSTALLDIR}/modules-enabled/*;
    do
        echo "Enabling ${module}...";
        CONFIG=${INSTALLDIR}/config ${module} enable;
    done;

    cp -aR ${INSTALLDIR}/data/advancedsettings.xml /data/.boxee/UserData/;
    sed -i 's/"hostname":"\([^;]*\);.*","p/"hostname":"\1","p/g' /data/etc/boxeehal.conf;
    sed -i 's/<hostname>\([^;]*\);.*<\/hostname>/<hostname>\1<\/hostname>/g' /data/.boxee/UserData/guisettings.xml;
    sed -i "s%\",\"password%;sh ${INSTALLDIR}/boxeehack start\",\"password%g" /data/etc/boxeehal.conf;
    sed -i "s%</hostname>%;sh ${INSTALLDIR}/boxeehack start\</hostname>%g" /data/.boxee/UserData/guisettings.xml;
    touch /data/etc/boxeehal.conf;
    touch /data/.boxee/UserData/guisettings.xml;

    echo "Boxee+Hacks installed!";
}

boxeehack_uninstall()
{
    echo "Uninstalling Boxee+Hacks";
    for module in ${INSTALLDIR}/modules-enabled/*;
    do
        echo "Disabling ${module}...";
        CONFIG=${INSTALLDIR}/config ${module} stop;
        CONFIG=${INSTALLDIR}/config ${module} disable;
    done;

    rm /data/.boxee/UserData/advancedsettings.xml;
    sed -i 's/"hostname":"\([^;]*\);.*","p/"hostname":"\1","p/g' /data/etc/boxeehal.conf;
    sed -i 's/<hostname>\([^;]*\);.*<\/hostname>/<hostname>\1<\/hostname>/g' /data/.boxee/UserData/guisettings.xml;
    touch /data/etc/boxeehal.conf;
    touch /data/.boxee/UserData/guisettings.xml;

    rm -Rf ${PERSISTENTDIR};
    echo "Boxee+Hacks uninstalled!";
}

boxeehack_module_enable()
{
    if [ -z "$1" ];
    then
        echo "Module name required!";
        exit 1;
    fi;

    if [ ! -x "${INSTALLDIR}/modules-available/$1" ];
    then
        echo "Module '$1' doesn't exist!";
        exit 2;
    fi;

    if [ -x "${INSTALLDIR}/modules-enabled/$1" ];
    then
        echo "Module '$1' already enabled!";
        exit 3;
    fi;

    ln -s ${INSTALLDIR}/modules-available/$1 ${INSTALLDIR}/modules-enabled/;
    CONFIG=${INSTALLDIR}/config ${INSTALLDIR}/modules-enabled/$1 enable;
}

boxeehack_module_disable()
{
    if [ -z "$1" ];
    then
        echo "Module name required!";
        exit 1;
    fi;

    if [ ! -x "${INSTALLDIR}/modules-available/$1" ];
    then
        echo "Module '$1' doesn't exist!";
        exit 2;
    fi;

    if [ ! -x "${INSTALLDIR}/modules-enabled/$1" ];
    then
        echo "Module '$1' not enabled!";
        exit 4;
    fi;

    CONFIG=${INSTALLDIR}/config ${INSTALLDIR}/modules-enabled/$1 stop;
    CONFIG=${INSTALLDIR}/config ${INSTALLDIR}/modules-enabled/$1 disable;
    rm ${INSTALLDIR}/modules-enabled/$1;
}

case "$1" in
    start)
        boxeehack_start $2;
    ;;

    stop)
        boxeehack_stop $2;
    ;;

    install)
        boxeehack_install;
    ;;

    uninstall)
        boxeehack_uninstall;
    ;;

    enable)
        boxeehack_module_enable $2;
    ;;

    disable)
        boxeehack_module_disable $2;
    ;;
esac;
