#!/bin/sh
INSTALLDIR="/data/hack";
PERSISTENTDIR="/data/hack-persistent";
_MODULES="/tmp/boxeehack-modules-started";
UPGRADESCRIPT="https://raw.github.com/neverouspl/boxeehack/modular/install/install.sh";
export PATH="${INSTALLDIR}/bin:$PATH";

started_module()
{
    touch ${_MODULES}/.$1;
}

require_modules()
{
    # that probably should be different
    for module in $@;
    do
        # waiting until file appears
        while [ ! -e "${_MODULES}/.${module}" ];
        do
            sleep 1;
        done;
    done;
}

stopped_module()
{
    rm -f ${_MODULES}/.$1;
}
